export class ChecklistMotoEntity {
  id!: number;
  tipo!: string;
  doc_propietario!: string;
  fec_vence_seguro!: string | null;
  fec_vence_cert_gases!: string | null;
  sede!: string;
  placa!: string;
  modelo!: string;
  marca!: string;
  linea!: string;
  conductor!: string;
  doc_conductor!: string;
  categoria_lic!: string | null;
  fec_vence_lic_conductor!: string | null;
  porta_documentos!: number;
  observacion_documentos!: string | null;
  fecha!: string;
  kilometraje!: number | null;
  fugas_lubricantes!: number;
  observacion_fugas_lubricantes!: string | null;
  fugas_combustible!: number;
  observacion_fugas_combustible!: string | null;
  exosto!: number;
  observacion_exosto!: string | null;
  estado_cadena!: number;
  observacion_estado_cadena!: string | null;
  estado_pinones!: number;
  observacion_estado_pinones!: string | null;
  estado_otra_trans!: number;
  observacion_estado_otra_trans!: string | null;
  amortiguadores!: number;
  observacion_amortiguadores!: string | null;
  barra_estab!: number;
  observacion_barra_estab!: string | null;
  fugas_frenos!: number;
  observacion_fugas_frenos!: string | null;
  estado_depo!: number;
  observacion_estado_depo!: string | null;
  estado_pastillas!: number;
  observacion_estado_pastillas!: string | null;
  estado_guayas!: number;
  observacion_estado_guayas!: string | null;
  estado_farola_princ!: number;
  observacion_estado_farola_princ!: string | null;
  luces_direccionales!: number;
  observacion_luces_direccionales!: string | null;
  pito!: number;
  observacion_pito!: string | null;
  luz_tacometro!: number;
  observacion_luz_tacometro!: string | null;
  indicador_velocimetro!: number;
  observacion_indicador_velocimetro!: string | null;
  indicador_combustible!: number;
  observacion_indicador_combustible!: string | null;
  testigo!: number;
  observacion_testigo!: string | null;
  llanta_del!: number;
  observacion_llanta_del!: string | null;
  llantas_tra!: number;
  observacion_llantas_tra!: string | null;
  presion_aire!: number;
  observacion_presion_aire!: string | null;
  cojineria!: number;
  observacion_cojineria!: string | null;
  guarda_barros!: number;
  observacion_guarda_barros!: string | null;
  manubrios!: number;
  observacion_manubrios!: string | null;
  parrilla!: number;
  observacion_parrilla!: string | null;
  retrovisores!: number;
  observacion_retrovisores!: string | null;
  latoneria!: number;
  observacion_latoneria!: string | null;
  kit_herramientas!: number;
  observacion_kit_herramientas!: string | null;
  casco!: number;
  observacion_casco!: string | null;
  chaleco!: number;
  observacion_chaleco!: string | null;
  rodilleras!: number;
  observacion_rodilleras!: string | null;
  impermeable!: number;
  observacion_impermeable!: string | null;
  botas_seg!: number;
  observacion_botas_seg!: string | null;
  hallazgo_1!: string | null;
  plan_accion_1!: string | null;
  fecha_1!: string | null;
  evidencia_1!: string | null;
  hallazgo_2!: string | null;
  plan_accion_2!: string | null;
  fecha_2!: string | null;
  evidencia_2!: string | null;

  constructor(partial: Partial<ChecklistMotoEntity>) {
    Object.assign(this, partial);
  }
}

