export type ChecklistTipo = 0 | 1 | 2 | 3 | 4 | 5 | 6;

export const CHECKLIST_TABLAS: Record<ChecklistTipo, string> = {
  0: 'swcrm_check_labor_calor',
  1: 'swcrm_check_alineador',
  2: 'swcrm_check_elevadores',
  3: 'swcrm_check_tijera',
  4: 'swcrm_check_hidraulicos',
  5: 'swcrm_check_portico',
  6: 'swcrm_check_cabina_pintura',
};

export const CHECKLIST_TITULOS: Record<ChecklistTipo, string> = {
  0: 'TRABAJOS EN CALIENTE',
  1: 'INSPECCIÓN PREOPERACIONAL DEL ELEVADOR DEL ALINEADOR',
  2: 'INSPECCIÓN PREOPERACIONAL DE ELEVADORES DE COLUMNA',
  3: 'INSPECCIÓN PREOPERACIONAL DE ELEVADORES TIJERA',
  4: 'INSPECCIÓN PREOPERACIONAL DE EQUIPOS HIDRÁULICOS',
  5: 'INSPECCIÓN PREOPERACIONAL DE PORTICO CON DIFERENCIAL',
  6: 'INSPECCIÓN PREOPERACIONAL DE CABINA DE PINTURA',
};

/** Columnas permitidas por tipo (whitelist SQL). */
export const CHECKLIST_COLUMNAS: Record<ChecklistTipo, readonly string[]> = {
  0: [
    'area_trabajo',
    'proposito_trabajo',
    'nombre_pa_1',
    'cedula_pa_1',
    'arl_pa_1',
    'eps_pa_1',
    'afp_pa_1',
    'nombre_pa_2',
    'cedula_pa_2',
    'arl_pa_2',
    'eps_pa_2',
    'afp_pa_2',
    'fecha',
    'sede',
    'procedimiento_claro',
    'disposicion_herramientas',
    'personal_calificado',
    'reunion_implicados',
    'area_ejecucion',
    'delimitacion_area',
    'guantes',
    'botas',
    'mascara',
    'careta_esmerilar',
    'gafas',
    'capucha',
    'delantal',
    'ropa_trabajo',
    'careta_soldadura',
    'trabajadores_entrenados',
    'epp_suficientes',
    'mamparas',
    'conexion_tierra',
    'disposicion_extintores',
    'materiales_protegidos',
    'area_libre_sustancias',
    'estado_equipos_usar',
    'cilindros_asegurados',
    'saber_apagar_fuego',
    'tuberias_aisladas',
    'precaucion_liberacion_gases',
    'valvula_marcada',
    'estado_cables_temporales',
    'area_aseada_terminar',
    'levantamiento_bloqueos',
    'colocar_controles',
    'plan_resp_emergencia',
    'observado_continuamente',
    'observacion_general',
    'entregado_equipo_terminar',
    'mediciones_gases',
  ],
  1: [
    'responsable',
    'equipo',
    'codigo',
    'area',
    'sede',
    'fecha',
    'estado_conexiones',
    'observacion_estado_conexiones',
    'guaya_acero',
    'observacion_guaya_acero',
    'rampas_acceso',
    'observacion_rampas_acceso',
    'controles',
    'observacion_controles',
    'seguros',
    'observacion_seguros',
    'operacion_vacio',
    'observacion_operacion_vacio',
    'elevacion_maxima',
    'observacion_elevacion_maxima',
    'sin_fugas',
    'observacion_sin_fugas',
    'pines_altura',
    'observacion_pines_altura',
    'estado_general',
    'observacion_estado_general',
    'sin_ruidos',
    'observacion_sin_ruidos',
    'obs_seguimiento',
  ],
  2: [
    'responsable',
    'equipo',
    'codigo',
    'area',
    'sede',
    'fecha',
    'estado_conexiones',
    'observacion_estado_conexiones',
    'estado_cadena',
    'observacion_estado_cadena',
    'brazos_elevador',
    'observacion_brazos_elevador',
    'controles',
    'observacion_controles',
    'seguros',
    'observacion_seguros',
    'operacion_vacio',
    'observacion_operacion_vacio',
    'elevacion_maxima',
    'observacion_elevacion_maxima',
    'sin_fugas',
    'observacion_sin_fugas',
    'pines_altura',
    'observacion_pines_altura',
    'cable_acero',
    'observacion_cable_acero',
    'almohadillas',
    'observacion_almohadillas',
    'estado_general',
    'observacion_estado_general',
    'obs_seguimiento',
  ],
  3: [
    'responsable',
    'equipo',
    'codigo',
    'area',
    'sede',
    'fecha',
    'estado_conexiones',
    'observacion_estado_conexiones',
    'ausencia_fugas',
    'observacion_ausencia_fugas',
    'plataformas_elevador',
    'observacion_plataformas_elevador',
    'controles',
    'observacion_controles',
    'seguros_neumaticos',
    'observacion_seguros_neumaticos',
    'operacion_vacio',
    'observacion_operacion_vacio',
    'parada_emergencia',
    'observacion_parada_emergencia',
    'estado_tacos',
    'observacion_estado_tacos',
    'estado_general',
    'observacion_estado_general',
    'sin_ruidos',
    'observacion_sin_ruidos',
    'obs_seguimiento',
  ],
  4: [
    'responsable',
    'equipo',
    'codigo',
    'area',
    'sede',
    'fecha',
    'funcionamiento_elevacion',
    'observacion_funcionamiento_elevacion',
    'fluidos_hidraulicos',
    'observacion_fluidos_hidraulicos',
    'ruedas',
    'observacion_ruedas',
    'estado_palas',
    'observacion_estado_palas',
    'sist_giro',
    'observacion_sist_giro',
    'peso_apropiado',
    'observacion_peso_apropiado',
    'carga_equilibrada',
    'observacion_carga_equilibrada',
    'dir_marcha',
    'observacion_dir_marcha',
    'soportes_carga',
    'observacion_soportes_carga',
    'obs_seguimiento',
  ],
  5: [
    'responsable',
    'equipo',
    'codigo',
    'sede',
    'fecha',
    'area_segura',
    'observacion_area_segura',
    'porta_epp',
    'observacion_porta_epp',
    'peso_apropiado',
    'observacion_peso_apropiado',
    'aldaba',
    'observacion_aldaba',
    'estado_gancho',
    'observacion_estado_gancho',
    'sist_giro',
    'observacion_sist_giro',
    'deformacion_eslabones',
    'observacion_deformacion_eslabones',
    'presenta_corrosion',
    'observacion_presenta_corrosion',
    'engranaje_funcional',
    'observacion_engranaje_funcional',
    'frenos',
    'observacion_frenos',
    'topes_desplazamiento',
    'observacion_topes_desplazamiento',
    'movimiento_trolley',
    'observacion_movimiento_trolley',
    'movilidad_llantas',
    'observacion_movilidad_llantas',
    'libre_abolladuras',
    'observacion_libre_abolladuras',
    'obs_seguimiento',
  ],
  6: [
    'responsable',
    'equipo',
    'codigo',
    'area',
    'sede',
    'fecha',
    'sistema_mandos',
    'observacion_sistema_mandos',
    'sistema_ventilacion',
    'observacion_sistema_ventilacion',
    'estado_filtros',
    'observacion_estado_filtros',
    'lamparas',
    'observacion_lamparas',
    'ruidos_extranos',
    'observacion_ruidos_extranos',
    'cierre_hermetico',
    'observacion_cierre_hermetico',
    'fuga_gas',
    'observacion_fuga_gas',
    'rejillas',
    'observacion_rejillas',
    'sistema_neumatico',
    'observacion_sistema_neumatico',
    'obs_seguimiento',
  ],
};

/** Campos booleanos en BD (cabina). */
export const CHECKLIST_BOOLEAN_COLUMNS: Partial<
  Record<ChecklistTipo, readonly string[]>
> = {
  6: [
    'sistema_mandos',
    'sistema_ventilacion',
    'estado_filtros',
    'lamparas',
    'ruidos_extranos',
    'cierre_hermetico',
    'fuga_gas',
    'rejillas',
    'sistema_neumatico',
  ],
};

export function isChecklistTipo(value: number): value is ChecklistTipo {
  return value >= 0 && value <= 6;
}

function asText(value: unknown): string {
  if (typeof value === 'string') return value;
  if (typeof value === 'number' && Number.isFinite(value)) return String(value);
  return '';
}

export function responsableFromData(
  check: ChecklistTipo,
  data: Record<string, unknown>,
): string {
  if (check === 0) {
    return asText(data.nombre_pa_1);
  }
  return asText(data.responsable);
}
