export class ChecklistCarroEntity {
  id!: number;
  tipo_vh!: string;
  placa!: string;
  fecha!: string;
  sede!: string;
  conductor!: string;
  doc_conductor!: string;
  lic_conduccion!: number;
  categoria_lic!: string | null;
  fec_vence_lic!: string | null;
  observacion_lic!: string | null;
  porta_documentos!: number;
  observacion_documentos!: string | null;
  sol_prueba_ruta!: number;
  asesor!: string | null;
  nombre_cliente!: string | null;
  cel_cliente!: string | null;
  fec_tecno!: string | null;
  tecno!: number;
  observacion_tecno!: string | null;
  fec_soat!: string | null;
  soat!: number;
  observacion_soat!: string | null;
  dir_delanteras!: number;
  observacion_dir_del!: string | null;
  dir_traseras!: number;
  observacion_dir_tra!: string | null;
  luces_altas!: number;
  observacion_altas!: string | null;
  luces_bajas!: number;
  observacion_bajas!: string | null;
  stops!: number;
  observacion_stops!: string | null;
  luces_reversa!: number;
  observacion_reversa!: string | null;
  luces_parqueo!: number;
  observacion_parqueo!: string | null;
  luces_internas!: number;
  observacion_internas!: string | null;
  limpia_parabrisas!: number;
  observacion_plumilla!: string | null;
  pito!: number;
  observacion_pito!: string | null;
  sist_direccion!: number;
  observacion_sist_dir!: string | null;
  cinturones!: number;
  observacion_cintu_seg!: string | null;
  airbag!: number;
  observacion_airbag!: string | null;
  frenos_princ!: number;
  observacion_frenos_prin!: string | null;
  frenos_emergencia!: number;
  observacion_frenos_emerg!: string | null;
  llantas!: number;
  observacion_llantas!: string | null;
  llanta_repto!: number;
  observacion_llanta_repto!: string | null;
  espejos!: number;
  observacion_espejos!: string | null;
  nivel_fluidos_frenos!: number;
  observacion_fluidos_frenos!: string | null;
  nivel_fluidos_aceite!: number;
  observacion_fluidos_aceite!: string | null;
  nivel_fluidos_refrigerante!: number;
  observacion_fluidos_refrig!: string | null;
  extintor!: number;
  fec_extintor!: string | null;
  observacion_extintor!: string | null;
  kit_carretera!: number;
  observacion_kit_carretera!: string | null;
  botiquin!: number;
  observacion_botiquin!: string | null;
  quinta_rueda!: number;
  observacion_quinta_rueda!: string | null;
  mangueras!: number;
  observacion_mangueras_aire!: string | null;
  nivel_combustible!: string | null;
  kilometraje_salida!: number | null;
  kilometraje_llegada!: number | null;
  observacion_general!: string | null;

  constructor(partial: Partial<ChecklistCarroEntity>) {
    Object.assign(this, partial);
  }
}

